### ISSUE TITLE
More Reporting On Number of Metrics Collected / Work Performed By Agent

### ISSUE THREAD

**Issue by JimHagan** [newrelic/nrjmx#114]
A customer is running an analysis on the impact of the running nrjmx agent on their environemment and see request duration average creep up when running.

Now the performance team wants to find better ways to know how many metrics are being processed in each run.  It's likely they may try to optimize the metric configurations based on these performance metrics.

- Can we configure debug log level and is it likely to show us the number of metrics processed per fetch
- Or can we consider having a rollup report on each run just saying how many metrics are gathered per each fetch per host

I will share two screenshots from the customer's benchmark environment:

*WITH nrjmx running*

<img width="891" alt="Screen Shot 2022-04-19 at 8 39 25 AM" src="https://user-images.githubusercontent.com/8333200/164008028-295bd624-495a-4ba7-9dae-dc4983d4c17e.png">

*WITHOUT nrjmx running*

<img width="887" alt="Screen Shot 2022-04-19 at 8 31 18 AM" src="https://user-images.githubusercontent.com/8333200/164008089-6c234ee0-19f4-43a3-a694-d1610c461685.png">

**Comment by josemore** [comment]
Thanks for sharing the performance insights @JimHagan 
There might be multiple approaches to get more insights. One way might be enabling the trace log level [v3.submission](https://github.com/newrelic/infrastructure-agent/blob/2aa24551aff4611a25e2ab1ec7754b26985ab048/assets/examples/infrastructure/newrelic-infra-template.yml.example#L716) which will print all requests made to the backend when pushing NR events. In correlation with verbose logs you should be able to see number of metrics being processed on each execution.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
