### ISSUE TITLE
MIgrating to Gradle

### ISSUE THREAD

**Issue by ysb33r** [newrelic/nrjmx#54]
- [x] Perform initial port via `gradle init`
- [x] Auto-module legacy JARs
- [x] Add JLink support
- [x] Build testserver from within testcontainers rather than using separate task
- ~~Check that generated POM is the same as what maven builds~~ (Not needed as the old project did not actually publish a jar).
- [x] Adapt functionality from `maven-assembly-plugin` if necessary
- [x] Adapt functionality from `copy-rename-maven-plugin` if necessary
- [x] Ensure generated tarball is close enough to what maven does
- [x] Create `deb` from Gradle
- [x] Create `rpm` from Gradle
- [x] Delete Maven build files

**Comment by ysb33r** [comment]
I've add RPM & DEB support. I am just manually testing installation of those packages atm. I could add testcontainer-based testing to test installation of the packages into respective containers, but I'm not sure if that should really be in scope of this change.

I've also noticed that `distTar`, `distZip` tasks actually packages according to the traditional way `application` plugin does and is not influenced by `jlink` plugin. I need to fix that.

//cc @kittylyst

**Comment by kittylyst** [comment]
PR merged. Closing this issue.
