### ISSUE TITLE
remoteJBossStandalone flag is ignored if -r is not provided

### ISSUE THREAD

**Issue by cristianciutea** [newrelic/nrjmx#64]
## Description
-remoteJBossStandalone flag is ignored if -r is not provided
## Expected Behavior
Improve configuration option so that only one flag(remoteJBossStandalone) need to be specified

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
