### ISSUE TITLE
Skip NaN values instead of assuming zeros

### ISSUE THREAD

**Issue by josemore** [newrelic/nrjmx#75]
There’s an assumption in [JMXFetcher.java](https://github.com/newrelic/nrjmx/blob/fda5cdc2ee063985f13f89f18a828be866180ac5/src/main/java/org/newrelic/nrjmx/JMXFetcher.java#L391) that converting from NaN to zero is always a good idea. For any sort of error metric I believe it’s a bad idea, because graphs would show a zero errors where in reality the agent doesn’t know. I think it makes more sense to skip the event than assume it’s zero.

Real world example: we track message lag of a Kafka consumer via JMX. If the consumer stops, the lag metrics increase, so we know there’s a problem to investigate. However, eventually most of the JMX metrics change to NaN because the consumer isn’t updating them anymore. Rather than report no value, the infrastructure agent reports zero messages lag, which in this case would be confusing and potentially mask a real issue.

Scope:
- Consider a backward compatible setting to avoid sending the attribute if the value is NaN. In the agent for some samplers, if there are null attributes, we don’t include that attribute into the json serialization but we still submit the event.

**Comment by cristianciutea** [comment]
In nrjmx v2.0.0 attributes that have NaN/inf values will not be reported at the backend. An warning message will be output in the agent logs. (Requires verbose:1)
